# Generated by Django 6.0.5 on 2026-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock Sandbox Simulator'), ('gemini', 'Google Gemini API'), ('openai', 'OpenAI API')], default='mock', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ROOT', max_length=100)),
                ('creation_type', models.CharField(choices=[('copy', 'Marketing Copywriting'), ('image', 'Social Media Image'), ('storyboard', 'Storyboard Script'), ('audio', 'AI Voiceover')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='JSON-serialized creation details')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('audio_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('rag_indexed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
