# Generated by Django 6.0.5 on 2026-06-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aiconfiguration_scope_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='task_type',
            field=models.CharField(choices=[('copy', 'Marketing Copywriting'), ('image', 'Social Media Image'), ('storyboard', 'Storyboard Script'), ('audio', 'AI Voiceover'), ('rag_search', 'Semantic Retrieval'), ('custom_agent', 'Custom Agent')], max_length=20),
        ),
    ]
