# Generated by Django 6.0.5 on 2026-06-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_auditlog_action_assistantsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('member_change', 'Member Change'), ('key_change', 'Key Change'), ('export', 'Export'), ('delete', 'Delete'), ('billing_change', 'Billing Change'), ('generation_create', 'Generation Create'), ('workflow_run', 'Workflow Run'), ('workflow_retry', 'Workflow Retry'), ('brainstorm', 'Brainstorm'), ('assistant_step', 'Assistant Step')], max_length=40),
        ),
    ]
