# Generated by Django 6.0.5 on 2026-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_video_model_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycreation',
            name='creation_type',
            field=models.CharField(choices=[('copy', 'Marketing Copywriting'), ('image', 'Social Media Image'), ('storyboard', 'Storyboard Script'), ('audio', 'AI Voiceover'), ('video', 'AI Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='task_type',
            field=models.CharField(choices=[('copy', 'Marketing Copywriting'), ('image', 'Social Media Image'), ('image_prompt', 'Image Prompt Engineering'), ('storyboard', 'Storyboard Script'), ('audio', 'AI Voiceover'), ('video', 'Marketing Video'), ('review', 'Content Review'), ('rag_search', 'Semantic Retrieval'), ('custom_agent', 'Custom Agent'), ('brainstorm', 'Workflow Brainstorm')], max_length=20),
        ),
    ]
