# Generated by Django 6.0.5 on 2026-06-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile_creator_page_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditledgerentry',
            new_name='api_creditl_organiz_94580d_idx',
            old_name='api_creditl_organiz_b2e57d_idx',
        ),
        migrations.RenameIndex(
            model_name='creditledgerentry',
            new_name='api_creditl_source_77683b_idx',
            old_name='api_creditl_source_602a5e_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='api_securit_event_t_48b48e_idx',
            old_name='api_securit_event_t_5590d3_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='api_securit_email_90473e_idx',
            old_name='api_securit_email_a_b1e1ca_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='api_securit_ip_addr_a74641_idx',
            old_name='api_securit_ip_addr_b8a3ea_idx',
        ),
    ]
