# Generated by Django 6.0.5 on 2026-06-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_api_creditl_organiz_b2e57d_idx_api_creditl_organiz_94580d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial_success', 'Partial Success'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('graph_version', models.CharField(default='v1', max_length=32)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('total_nodes', models.IntegerField(default=0)),
                ('completed_nodes', models.IntegerField(default=0)),
                ('failed_nodes', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('actual_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='api.campaign')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='api.workspacedraft')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='api.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='api.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=120)),
                ('node_type', models.CharField(max_length=40)),
                ('node_label', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('saving_asset', 'Saving Asset'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('attempt', models.IntegerField(default=1)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_node_runs', to='api.generationtask')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='api.workflownoderun')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='api.workflowrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('node_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.workflownoderun')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.workflowrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='api_workflo_organiz_50a34b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['draft', 'status'], name='api_workflo_draft_i_8e8fff_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['workflow_run', 'status'], name='api_workflo_workflo_202bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['generation_task'], name='api_workflo_generat_e169ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflownoderun',
            unique_together={('workflow_run', 'node_id', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='workflowrunevent',
            index=models.Index(fields=['workflow_run', 'created_at'], name='api_workflo_workflo_b6a8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrunevent',
            index=models.Index(fields=['event_type'], name='api_workflo_event_t_7bb177_idx'),
        ),
    ]
