# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_visibility(apps, schema_editor):
    CommunityCreation = apps.get_model('api', 'CommunityCreation')
    CommunityCreation.objects.filter(visibility='private').update(visibility='organization')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_workflowrun_workflownoderun_workflowrunevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycreation',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('private', 'Private'),
                    ('organization', 'Organization'),
                    ('public', 'Public'),
                ],
                default='private',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='published_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_creations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(initialize_visibility, migrations.RunPython.noop),
    ]
