# Generated by Codex on 2026-06-27

from django.db import migrations, models


def encrypt_existing_keys(apps, schema_editor):
    from api.crypto import encrypt_secret, fingerprint_secret

    AIConfiguration = apps.get_model('api', 'AIConfiguration')
    for config in AIConfiguration.objects.exclude(api_key='').iterator():
        raw_key = (config.api_key or '').strip()
        if not raw_key:
            continue
        config.api_key_encrypted = encrypt_secret(raw_key)
        config.api_key_fingerprint = fingerprint_secret(raw_key)
        config.api_key_last4 = raw_key[-4:]
        config.api_key = ''
        config.save(
            update_fields=[
                'api_key',
                'api_key_encrypted',
                'api_key_fingerprint',
                'api_key_last4',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_communitycreation_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='api_key_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='api_key_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='key_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_keys, migrations.RunPython.noop),
    ]
