# Generated by Django 6.0.5 on 2026-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_encrypt_ai_configuration_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('member_change', 'Member Change'), ('key_change', 'Key Change'), ('ai_key_create', 'AI Key Create'), ('ai_key_update', 'AI Key Update'), ('ai_key_delete', 'AI Key Delete'), ('ai_key_validate', 'AI Key Validate'), ('export', 'Export'), ('delete', 'Delete'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_delete', 'Project Delete'), ('folder_create', 'Folder Create'), ('folder_update', 'Folder Update'), ('folder_delete', 'Folder Delete'), ('campaign_create', 'Campaign Create'), ('campaign_update', 'Campaign Update'), ('campaign_delete', 'Campaign Delete'), ('asset_create', 'Asset Create'), ('asset_update', 'Asset Update'), ('asset_delete', 'Asset Delete'), ('community_publish', 'Community Publish'), ('community_unpublish', 'Community Unpublish'), ('billing_change', 'Billing Change'), ('credit_grant', 'Credit Grant'), ('generation_create', 'Generation Create'), ('workflow_run', 'Workflow Run'), ('workflow_retry', 'Workflow Retry'), ('brainstorm', 'Brainstorm'), ('assistant_step', 'Assistant Step'), ('cross_org_access_denied', 'Cross-org Access Denied')], max_length=40),
        ),
    ]
