# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
