# Generated by Django 6.0.5 on 2026-06-27 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_beta_policy_documents(apps, schema_editor):
    PolicyDocument = apps.get_model('api', 'PolicyDocument')
    docs = [
        ('terms', '2026-06-27-beta', 'Marketing Hub 服务条款（Beta）', '/legal/terms'),
        ('privacy', '2026-06-27-beta', 'Marketing Hub 隐私政策（Beta）', '/legal/privacy'),
        ('ai_usage', '2026-06-27-beta', 'AI 生成内容使用规则（Beta）', '/legal/ai-usage'),
        ('community', '2026-06-27-beta', '社区发布规则（Beta）', '/legal/community'),
        ('asset_rights', '2026-06-27-beta', '素材上传授权声明（Beta）', '/legal/asset-rights'),
        ('billing', '2026-06-27-beta', '订阅、额度、退款和发票规则（Beta）', '/legal/billing'),
        ('byok', '2026-06-27-beta', 'BYOK 数据处理和密钥安全说明（Beta）', '/legal/byok'),
    ]
    for policy_type, version, title, content_url in docs:
        PolicyDocument.objects.get_or_create(
            policy_type=policy_type,
            version=version,
            defaults={
                'title': title,
                'content_url': content_url,
                'is_active': True,
                'effective_at': django.utils.timezone.now(),
            },
        )


def unseed_beta_policy_documents(apps, schema_editor):
    PolicyDocument = apps.get_model('api', 'PolicyDocument')
    PolicyDocument.objects.filter(version='2026-06-27-beta').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auditlog_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycreation',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('removed', 'Removed'), ('appealed', 'Appealed')], default='visible', max_length=24),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='reported_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='not_reviewed', max_length=24),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='api.asset'),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='api.generationtask'),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='takedown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitycreation',
            name='takedown_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('member_change', 'Member Change'), ('key_change', 'Key Change'), ('ai_key_create', 'AI Key Create'), ('ai_key_update', 'AI Key Update'), ('ai_key_delete', 'AI Key Delete'), ('ai_key_validate', 'AI Key Validate'), ('export', 'Export'), ('delete', 'Delete'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_delete', 'Project Delete'), ('folder_create', 'Folder Create'), ('folder_update', 'Folder Update'), ('folder_delete', 'Folder Delete'), ('campaign_create', 'Campaign Create'), ('campaign_update', 'Campaign Update'), ('campaign_delete', 'Campaign Delete'), ('asset_create', 'Asset Create'), ('asset_update', 'Asset Update'), ('asset_delete', 'Asset Delete'), ('community_publish', 'Community Publish'), ('community_unpublish', 'Community Unpublish'), ('content_report', 'Content Report'), ('content_moderation', 'Content Moderation'), ('policy_consent', 'Policy Consent'), ('billing_change', 'Billing Change'), ('credit_grant', 'Credit Grant'), ('generation_create', 'Generation Create'), ('workflow_run', 'Workflow Run'), ('workflow_retry', 'Workflow Retry'), ('brainstorm', 'Brainstorm'), ('assistant_step', 'Assistant Step'), ('cross_org_access_denied', 'Cross-org Access Denied')], max_length=40),
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookie', 'Cookie and SDK Notice'), ('ai_usage', 'AI Generated Content Rules'), ('community', 'Community Rules'), ('asset_rights', 'Asset Upload Rights'), ('billing', 'Billing and Refund Rules'), ('byok', 'BYOK Data Processing')], max_length=32)),
                ('version', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('content_url', models.CharField(max_length=600)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['policy_type', '-effective_at'],
                'indexes': [models.Index(fields=['policy_type', 'is_active', '-effective_at'], name='api_policyd_policy__bd1629_idx')],
                'unique_together': {('policy_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('community_creation', 'Community Creation'), ('asset', 'Asset')], max_length=40)),
                ('target_id', models.CharField(max_length=80)),
                ('reason', models.CharField(choices=[('illegal', 'Illegal Content'), ('infringement', 'IP Infringement'), ('false_advertising', 'False Advertising'), ('privacy', 'Privacy Disclosure'), ('unsafe_ai', 'Unsafe AI Output'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=24)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_content_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='api.organization')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'status'], name='api_content_target__1868d7_idx'), models.Index(fields=['organization', 'status', '-created_at'], name='api_content_organiz_d06297_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=32)),
                ('policy_version', models.CharField(max_length=40)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consented_at'],
                'indexes': [models.Index(fields=['user', 'policy_type', '-consented_at'], name='api_usercon_user_id_c2018f_idx'), models.Index(fields=['policy_type', 'policy_version'], name='api_usercon_policy__4a9334_idx')],
                'unique_together': {('user', 'policy_type', 'policy_version')},
            },
        ),
        migrations.RunPython(seed_beta_policy_documents, unseed_beta_policy_documents),
    ]
