# Generated by Django 6.0.5 on 2026-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_personal_billing_pro_invites"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
