# Generated by Django 6.0.5 on 2026-07-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_add_deleted_at_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="api.folder",
            ),
        ),
    ]
