changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Highlights
      labels:
        - highlight
    - title: New features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - chore
    - title: Other changes
      labels:
        - "*"
